name: 'Meli Static Deploy Github Action'
description: 'Deploy site build to Meli static sites hosting (or remove old branch and releases)'
author: 'Digital Vision CZ <software@digitalvision.cz>'

inputs:
  action:
    description: 'Meli action type [release,remove]'
    required: true
  meliUrl:
    description: 'Meli base url'
    required: true
  meliSiteId:
    description: 'Meli site id'
    required: true
  meliSiteToken:
    description: 'Meli site token'
    required: false
  meliApiToken:
    description: 'Meli API token'
    required: false
  meliSiteRelease:
    description: 'Meli site release name'
    required: false
  branchName:
    description: 'Branch name (subdomain in Meli site)'
    required: false
  buildFolder:
    description: 'Build folder (relative path from root, ie. dist)'
    default: 'dist'
    required: false

outputs:
  meliDeployUrl:
    description: 'URL of deployed release'

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: 'upload'
  color: 'gray-dark'
