name: Deploy preview on branch push
on:
  # run action on push on devel and feature branches
  push:
    branches:
      - main
      - develop
      - feature/*

jobs:
  # ... other jobs (ie linting, testing,..)
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: c-hive/gha-yarn-cache@v1
      - name: Install dependencies
        run: yarn
      - name: Build static files
        run: yarn build

      - name: Deploy static site preview # name your deploy step
        uses: digitalvisioncz/meli-deploy-github-action@1.0.0-beta.2 # use this Github action
        id: meli # set step ID (optional, but reuired if you want to use action's outputs)
        with:
          action: release # set Meli action
          meliUrl: https://meli.dvdev.cz # set Meli base URL
          meliSiteId: ${{ secrets.MELI_SITE_ID }} # set Meli site ID (use env or secrets)
          meliSiteToken: ${{ secrets.MELI_SITE_TOKEN }} # set Meli site token (use env or secrets)
          buildFolder: out # set yout build folder (from root of your repository)
